title: Cayman theme
description: Cayman is a clean, responsive theme for GitHub Pages.
author: André Pedersen
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll-feed # add this to enable RSS feed