theme: jekyll-theme-cayman

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

title: [FastPathology]
description: [Open platform for deep learning-based research and decision support in digital pathology]
show_downloads: [true]
