name: Screenshot Website

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    steps:
    - name: Screenshot Website
      uses: swinton/screenshot-website@v1.x
      with:
        source: https://andreped.github.io/fastpathology.github.io/
        destination: screenshot.png